---   Ques 1    Retrieve the first 10 rows from the "Customer" table.
---   Ques 2    List all products and their corresponding product categories from the "Product" and "ProductCategory" tables.
---   Ques 3    Find the total number of orders in the "SalesOrderHeader" table.
---   Ques 4    Display the top 5 customers based on their total order amount.
---   Ques 5    Retrieve all distinct job titles from the "Employee" table.
---   Ques 6    List all products with a list price greater than $500.
---   Ques 7    Find the average order amount for each customer from the "SalesOrderHeader" table.
---   Ques 8    Retrieve all orders placed by customers with the title "Mr."
---   Ques 9    Display the name and standard cost of products in descending order of standard cost.
---   Ques 10    List all employees and their respective managers' names from the "Employee" table.
---   Ques 11    Retrieve the names and addresses of all customers who are located in the state of California.
---   Ques 12    List all products with a list price between $100 and $500, ordered by list price in ascending order.
---   Ques 13    Find the total number of employees in each department from the "Employee" table.
---   Ques 14    Display the first and last names of employees who have the same first name as their manager.
---   Ques 15    Retrieve the top 5 customers with the highest credit limit.
---   Ques 16    List all products with their corresponding product categories and subcategories.
---   Ques 17    Find the total sales amount for each year and month from the "SalesOrderHeader" table.
---   Ques 18    Display the name, email, and phone number of customers who have placed more than 5 orders.
---   Ques 19    Retrieve all employees who were hired between '2010-01-01' and '2015-12-31'.
---   Ques 20    List the products with a reorder point less than the average reorder point for all products.
---   Ques 21    Retrieve the names and phone numbers of customers who have placed at least one order but have not been assigned a sales representative.
---   Ques 22    List the products with their average rating and the number of reviews they have received.
---   Ques 23    Find the total number of orders for each employee in the "SalesOrderHeader" table.
---   Ques 24    Display the top 5 product categories with the highest number of unique products.
---   Ques 25    Retrieve the name and job title of employees who have a job title containing the word "Manager."
---   Ques 26    List all customers who have a credit limit greater than the average credit limit of all customers.
---   Ques 27    Find the total sales amount for each customer from the "SalesOrderHeader" table, excluding the customers with no sales.
---   Ques 28    Display the names and email addresses of employees whose job titles start with the letter "S."
---   Ques 29    Retrieve the products with their respective colors from the "Product" and "ProductProductPhoto" tables.
---   Ques 30    List the products that have been discontinued.
